# Generated by Django 4.1.7 on 2023-05-19 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoapNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_visit', models.CharField(max_length=15)),
                ('subjective', models.TextField(blank=True)),
                ('objective', models.TextField(blank=True)),
                ('assessment', models.TextField(blank=True)),
                ('plan', models.TextField(blank=True)),
                ('comments', models.TextField(blank=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='SoapNotes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='labscientist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pharmacist',
            name='user',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Labscientist',
        ),
        migrations.DeleteModel(
            name='Nurse',
        ),
        migrations.DeleteModel(
            name='Pharmacist',
        ),
    ]
