# Generated by Django 4.1.7 on 2023-05-20 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0003_alter_soapnotes_subjective'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soapnotes',
            name='created_by',
        ),
    ]
