# Generated by Django 4.1.7 on 2023-05-20 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0004_remove_soapnotes_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soapnotes',
            name='patient',
        ),
    ]
