# Generated by Django 4.1.7 on 2023-05-20 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_remove_patient_user'),
        ('personnel', '0005_remove_soapnotes_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='soapnotes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='soapnotes',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='soapnote', to='patient.patient'),
            preserve_default=False,
        ),
    ]
