# Generated by Django 4.1.7 on 2023-05-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0007_soapnotes_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soapnotes',
            name='created_by',
            field=models.CharField(max_length=15),
        ),
    ]
