# Generated by Django 4.1.7 on 2023-05-20 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0008_alter_soapnotes_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soapnotes',
            old_name='created_by',
            new_name='recorded_by',
        ),
    ]
