# Generated by Django 4.1.7 on 2023-05-20 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personnel', '0009_rename_created_by_soapnotes_recorded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soapnotes',
            name='recorded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soap', to=settings.AUTH_USER_MODEL),
        ),
    ]
