# Generated by Django 4.1.7 on 2023-05-20 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0013_alter_soapnotes_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soapnotes',
            name='user',
        ),
    ]
