# Generated by Django 4.1.7 on 2023-05-24 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0006_requestlabtest_lab'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlabtest_lab',
            name='biochemistry',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestlabtest_lab',
            name='haematology',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestlabtest_lab',
            name='microbiology',
            field=models.TextField(blank=True, null=True),
        ),
    ]
