# Generated by Django 4.1.7 on 2023-05-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0007_requestlabtest_lab_biochemistry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlabtest_lab',
            name='date_of_visit',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
