# Generated by Django 4.1.7 on 2023-05-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0010_requestdrugdispensing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestdrugdispensing',
            old_name='drugs',
            new_name='diagnosis',
        ),
        migrations.AddField(
            model_name='requestdrugdispensing',
            name='medicine_dosage',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
