# Generated by Django 4.1.7 on 2023-06-03 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0013_recordtestaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordtestaction',
            name='test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='record_testaction', to='record.recordlabresult'),
            preserve_default=False,
        ),
    ]
