# Generated by Django 4.1.7 on 2023-06-03 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_alter_patient_contact_person_phone'),
        ('record', '0014_recordtestaction_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordtestaction',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_testaction_pat', to='patient.patient'),
        ),
        migrations.AlterField(
            model_name='recordtestaction',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_testaction_tst', to='record.recordlabresult'),
        ),
    ]
