# Generated by Django 4.1.7 on 2023-06-03 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0015_alter_recordtestaction_patient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordtestaction',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='recordtestaction',
            name='test',
        ),
    ]
