# Generated by Django 4.1.7 on 2023-06-03 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0016_remove_recordtestaction_patient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordtestaction',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='recordtestaction',
            name='created_by',
        ),
    ]
