# Generated by Django 4.1.7 on 2023-06-03 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_alter_patient_contact_person_phone'),
        ('record', '0017_remove_recordtestaction_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordtestaction',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='record_testaction_pat', to='patient.patient'),
            preserve_default=False,
        ),
    ]
