# Generated by Django 4.1.7 on 2023-06-03 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0018_recordtestaction_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordtestaction',
            name='patient',
        ),
    ]
