# Generated by Django 4.1.7 on 2023-06-03 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_alter_patient_contact_person_phone'),
        ('record', '0019_remove_recordtestaction_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordtestaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='recordtestaction',
            name='created_by',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recordtestaction',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='record_testaction_pat', to='patient.patient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recordtestaction',
            name='test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='record_testaction_tst', to='record.recordlabresult'),
            preserve_default=False,
        ),
    ]
