# Generated by Django 4.1.7 on 2023-06-03 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0021_remove_recordtestaction_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordtestaction',
            name='created_at',
        ),
    ]
