# Generated by Django 4.1.7 on 2023-06-03 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_alter_patient_contact_person_phone'),
        ('record', '0022_remove_recordtestaction_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordTest_Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_result', models.TextField()),
                ('created_by', models.CharField(max_length=15)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_testaction_pat', to='patient.patient')),
            ],
        ),
        migrations.DeleteModel(
            name='RecordTestAction',
        ),
    ]
