# Generated by Django 4.1.7 on 2023-06-03 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0023_recordtest_action_delete_recordtestaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordtest_action',
            name='patient',
        ),
    ]
