# Generated by Django 4.1.7 on 2023-06-03 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0024_remove_recordtest_action_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordtest_action',
            name='test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='record_testaction', to='record.requestlabtest_lab'),
            preserve_default=False,
        ),
    ]
