# Generated by Django 4.1.7 on 2023-06-03 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0025_recordtest_action_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordTestAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_result', models.TextField()),
                ('created_by', models.CharField(max_length=15)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_testaction', to='record.requestlabtest_lab')),
            ],
        ),
        migrations.DeleteModel(
            name='RecordTest_Action',
        ),
    ]
