# Generated by Django 4.1.7 on 2023-06-03 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_patient_address_patient_contact_person_and_more'),
        ('record', '0027_remove_dispensedrugs_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispensedrugs',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='dispensedrugs',
            name='created_by',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dispensedrugs',
            name='date_of_visit',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dispensedrugs',
            name='diagnosis',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dispensedrugs',
            name='med1_dose',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dispensedrugs',
            name='med2_dose',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='dispensedrugs',
            name='med3_dose',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='dispensedrugs',
            name='med4_dose',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='dispensedrugs',
            name='med5_dose',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='dispensedrugs',
            name='med6_dose',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='dispensedrugs',
            name='medicine_1',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dispensedrugs',
            name='medicine_2',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='dispensedrugs',
            name='medicine_3',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='dispensedrugs',
            name='medicine_4',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='dispensedrugs',
            name='medicine_5',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='dispensedrugs',
            name='medicine_6',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='dispensedrugs',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dispense_drug', to='patient.patient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recordlabresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='recordlabresult',
            name='created_by',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recordlabresult',
            name='date_of_visit',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recordlabresult',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='record_labresult', to='patient.patient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recordtestaction',
            name='created_by',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recordtestaction',
            name='test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='record_testaction', to='record.requestlabtest_lab'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recordtestaction',
            name='test_result',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestdrugdispensing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='requestdrugdispensing',
            name='created_by',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestdrugdispensing',
            name='date_of_visit',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestdrugdispensing',
            name='diagnosis',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestdrugdispensing',
            name='medicine_dosage',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestdrugdispensing',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='request_drugdispensing', to='patient.patient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestlabtest_lab',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='requestlabtest_lab',
            name='created_by',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestlabtest_lab',
            name='date_of_visit',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestlabtest_lab',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='request_labtest_lab', to='patient.patient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestlabtest_lab',
            name='tests',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requesttriagenurse',
            name='comment',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requesttriagenurse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='requesttriagenurse',
            name='created_by',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requesttriagenurse',
            name='date_of_visit',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requesttriagenurse',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='request_triagenurse', to='patient.patient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soapnotes',
            name='assessment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='soapnotes',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='soapnotes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='soapnotes',
            name='created_by',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soapnotes',
            name='date_of_visit',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soapnotes',
            name='objective',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='soapnotes',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='soapnote', to='patient.patient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soapnotes',
            name='plan',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='soapnotes',
            name='subjective',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='triage',
            name='bmi',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='triage',
            name='bp',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='triage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='triage',
            name='created_by',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='triage',
            name='date_of_visit',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='triage',
            name='height',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='triage',
            name='lmp',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='triage',
            name='medication',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='triage',
            name='nurse_report',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='triage',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='triage', to='patient.patient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='triage',
            name='pulse',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='triage',
            name='respiration',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='triage',
            name='spo2',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='triage',
            name='temp',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='triage',
            name='weight',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
