# Generated by Django 4.1.7 on 2023-06-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0030_remove_recordtestaction_record_lab'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordtestaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
