# Generated by Django 4.1.7 on 2023-06-03 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_patient_address_patient_contact_person_and_more'),
        ('record', '0032_remove_recordtestaction_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordtestaction',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='record_testaction_pat', to='patient.patient'),
            preserve_default=False,
        ),
    ]
