# Generated by Django 4.1.7 on 2023-06-03 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0033_recordtestaction_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordtestaction',
            name='requestlabtest_lab',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='requestlabtest_lab', to='record.requestlabtest_lab'),
            preserve_default=False,
        ),
    ]
