# Generated by Django 4.1.7 on 2023-06-15 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0034_recordtestaction_requestlabtest_lab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordlabresult',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='recordtestaction',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='recordtestaction',
            name='requestlabtest_lab',
        ),
        migrations.DeleteModel(
            name='DispenseDrugs',
        ),
        migrations.DeleteModel(
            name='RecordLabResult',
        ),
        migrations.DeleteModel(
            name='RecordTestAction',
        ),
    ]
